### ISSUE TITLE
JCD-003: merge dist enhance

### ISSUE THREAD

**Issue by kylinsoong** [jbosschina/cluster#3]
Current build
        mvn clean install -P release
can generate 2 dist 
* jbosscache/demo/target/jbosscache-replication-demo-2.0-SNAPSHOT-dist.zip
* build/target/cluster-demo-dist.zip

Now, we need merge these 2 dist as one, which named cluster-demo-dist.zip, under 'build/target/' dir

**Comment by gaol** [comment]
A quick build locally generates only one zip file: build/target/cluster-demo-dist.zip.

module: **jbosscache** is not enabled at all, even is enabled, the java source failed to be compiled because of many non-imported classes in the java sources. Even import those missing imported classes, it generates only a regular jar file instead of a zip file.

All test are done against last **master** branch.

**Comment by kylinsoong** [comment]
I forgot synch code base, before transfer owner to jbosschina, now all be pushed on.

You may need synch a forking, 'Syncing a fork' section of below link may help.
    http://ksoong.org/git-commands/

**Comment by kylinsoong** [comment]
I have merged it
